apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-weather-app
  namespace: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-weather-app
  template:
    metadata:
      labels:
        app: react-weather-app
    spec:
      containers:
      - name: react-weather-app
        image: react-weather-app:latest
        ports:
        - containerPort: 8080
