apiVersion: v1
kind: Service
metadata:
  name: react-weather-app-service
  namespace: react-frontend
spec:
  selector:
    app: react-weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
